version: 2
jobs:
  lint:
    docker:
    - image: circleci/golang:1.11.4
    environment:
      GO111MODULE: "on"
      SHELL: /bin/bash
    working_directory: /go/src/github.com/ShyftNetwork/blockexplorer_api
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: make install
    - run:
        name: Lint
        command: make lint